services:
  - type: web
    name: crypto-analytics-backend
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements-simple.txt
    startCommand: python app/main_simple.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000
